In [1]:
import pandas as pd

demo = pd.read_sas("data/DEMO_J.xpt")
bp = pd.read_sas("data/BPX_J.xpt")
kidney = pd.read_sas("data/ALB_CR_J.xpt")

print("DEMO shape:", demo.shape)
print("BP shape:", bp.shape)
print("KIDNEY shape:", kidney.shape)

DEMO shape: (9254, 46)
BP shape: (8704, 21)
KIDNEY shape: (7936, 8)

In [2]:
demo.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
0,93703.0,10.0,2.0,2.0,2.0,NaN,5.0,6.0,2.0,27.0,...,3.0,1.0,3.0,9246.491865,8539.731348,2.0,145.0,15.0,15.0,5.00
1,93704.0,10.0,2.0,1.0,2.0,NaN,3.0,3.0,1.0,33.0,...,3.0,1.0,2.0,37338.768343,42566.614750,1.0,143.0,15.0,15.0,5.00
2,93705.0,10.0,2.0,2.0,66.0,NaN,4.0,4.0,2.0,NaN,...,1.0,2.0,NaN,8614.571172,8338.419786,2.0,145.0,3.0,3.0,0.82
3,93706.0,10.0,2.0,1.0,18.0,NaN,5.0,6.0,2.0,222.0,...,3.0,1.0,2.0,8548.632619,8723.439814,2.0,134.0,NaN,NaN,NaN
4,93707.0,10.0,2.0,1.0,13.0,NaN,5.0,7.0,2.0,158.0,...,2.0,1.0,3.0,6769.344567,7064.609730,1.0,138.0,10.0,10.0,1.88

In [3]:
bp.head()

,SEQN,PEASCCT1,BPXCHR,BPAARM,BPACSZ,BPXPLS,BPXPULS,BPXPTY,BPXML1,BPXSY1,...,BPAEN1,BPXSY2,BPXDI2,BPAEN2,BPXSY3,BPXDI3,BPAEN3,BPXSY4,BPXDI4,BPAEN4
0,93703.0,NaN,120.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,NaN,114.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,NaN,NaN,1.0,4.0,52.0,1.0,1.0,220.0,NaN,...,NaN,NaN,NaN,NaN,202.0,62.0,2.0,198.0,74.0,2.0
3,93706.0,NaN,NaN,1.0,3.0,82.0,1.0,1.0,140.0,112.0,...,2.0,114.0,70.0,2.0,108.0,76.0,2.0,NaN,NaN,NaN
4,93707.0,NaN,NaN,1.0,2.0,100.0,1.0,1.0,140.0,128.0,...,2.0,128.0,46.0,2.0,128.0,58.0,2.0,NaN,NaN,NaN

In [4]:
kidney.head()

,SEQN,URXUMA,URXUMS,URDUMALC,URXUCR,URXCRS,URDUCRLC,URDACT
0,93705.0,3.2,3.2,5.397605e-79,24.0,2121.6,5.397605e-79,13.33
1,93706.0,39.6,39.6,5.397605e-79,69.0,6099.6,5.397605e-79,57.39
2,93707.0,41.6,41.6,5.397605e-79,209.0,18475.6,5.397605e-79,19.90
3,93708.0,9.1,9.1,5.397605e-79,47.0,4154.8,5.397605e-79,19.36
4,93709.0,26.4,26.4,5.397605e-79,215.0,19006.0,5.397605e-79,12.28

In [5]:
# Now actual Cleaning of Data. Going to select those column that are actually needed and useful.

In [6]:
# Demographics (Age, Gender, BMI)
# SEQN = participant ID 
# RIDAGEYR = age
# RIAGENDR = gender
# Cleaning demographic data
demo_sel = demo[['SEQN', 'RIDAGEYR', 'RIAGENDR']]
demo_sel.head()

      SEQN  RIDAGEYR  RIAGENDR
0  93703.0       2.0       2.0
1  93704.0       2.0       1.0
2  93705.0      66.0       2.0
3  93706.0      18.0       1.0
4  93707.0      13.0       1.0

In [7]:
#  BP cleaning
bp_sel = bp[['SEQN', 'BPXSY1', 'BPXDI1']]
bp_sel.head()

      SEQN  BPXSY1  BPXDI1
0  93703.0     NaN     NaN
1  93704.0     NaN     NaN
2  93705.0     NaN     NaN
3  93706.0   112.0    74.0
4  93707.0   128.0    38.0

In [8]:
# Kidney  data cleaning 
kidney_sel = kidney[['SEQN', 'URXUCR', 'URXUMA']]
kidney_sel.head()

      SEQN  URXUCR  URXUMA
0  93705.0    24.0     3.2
1  93706.0    69.0    39.6
2  93707.0   209.0    41.6
3  93708.0    47.0     9.1
4  93709.0   215.0    26.4

In [9]:
# mergeing all dataset
#merge demographics and BP data
df = pd.merge(demo_sel, bp_sel, on='SEQN', how='inner')
print(df.shape)

(8704, 5)

In [10]:
# Merge kidney data
df = pd.merge(df, kidney_sel, on='SEQN', how='inner')
print(df.shape)

(7936, 7)

In [11]:
# Final Preview
df.head()

      SEQN  RIDAGEYR  RIAGENDR  BPXSY1  BPXDI1  URXUCR  URXUMA
0  93705.0      66.0       2.0     NaN     NaN    24.0     3.2
1  93706.0      18.0       1.0   112.0    74.0    69.0    39.6
2  93707.0      13.0       1.0   128.0    38.0   209.0    41.6
3  93708.0      66.0       2.0     NaN     NaN    47.0     9.1
4  93709.0      75.0       2.0   120.0    66.0   215.0    26.4

In [12]:
# check for missing values 
df.isnull().sum()

SEQN           0
RIDAGEYR       0
RIAGENDR       0
BPXSY1      1634
BPXDI1      1634
URXUCR       304
URXUMA       304
dtype: int64

In [13]:
# removing missing values 
df_clean = df.dropna()
print("Before cleaning:", df.shape)
print("After cleaning:", df_clean.shape)

Before cleaning: (7936, 7)
After cleaning: (6166, 7)

In [14]:
# Final cleaned preview
df_clean.head()

      SEQN  RIDAGEYR  RIAGENDR  BPXSY1  BPXDI1  URXUCR  URXUMA
1  93706.0      18.0       1.0   112.0    74.0    69.0    39.6
2  93707.0      13.0       1.0   128.0    38.0   209.0    41.6
4  93709.0      75.0       2.0   120.0    66.0   215.0    26.4
5  93711.0      56.0       1.0   108.0    68.0    98.0     3.7
6  93712.0      18.0       1.0   112.0    68.0    18.0     0.7

In [15]:
def kidney_risk(row):
    if row['URXUMA'] > 30 or row['URXUCR'] > 150:
        return 'High'
    elif row['URXUCR'] > 100:
        return 'Medium'
    else:
        return 'Low'

In [16]:
df_clean['kidney_risk'] = df_clean.apply(kidney_risk, axis=1)

C:\Users\DELL\AppData\Local\Temp\ipykernel_9820\2109998590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['kidney_risk'] = df_clean.apply(kidney_risk, axis=1)

In [17]:
df_clean['kidney_risk'].value_counts()

kidney_risk
High      2559
Low       2387
Medium    1220
Name: count, dtype: int64

In [18]:
df_clean.head()
#preview of final labeled data

      SEQN  RIDAGEYR  RIAGENDR  BPXSY1  BPXDI1  URXUCR  URXUMA kidney_risk
1  93706.0      18.0       1.0   112.0    74.0    69.0    39.6        High
2  93707.0      13.0       1.0   128.0    38.0   209.0    41.6        High
4  93709.0      75.0       2.0   120.0    66.0   215.0    26.4        High
5  93711.0      56.0       1.0   108.0    68.0    98.0     3.7         Low
6  93712.0      18.0       1.0   112.0    68.0    18.0     0.7         Low

In [19]:
# changing column name
df_final = df_clean.rename(columns={
    'RIDAGEYR': 'age',
    'RIAGENDR': 'gender',
    'BPXSY1': 'systolic_bp',
    'BPXDI1': 'diastolic_bp',
    'URXUCR': 'urine_creatinine',
    'URXUMA': 'urine_albumin'
})

In [20]:
# selecting final columns after renaming them
df_final = df_final[[
    'age',
    'gender',
    'systolic_bp',
    'diastolic_bp',
    'urine_creatinine',
    'urine_albumin',
    'kidney_risk'
]]

In [21]:
df_final.head()

,age,gender,systolic_bp,diastolic_bp,urine_creatinine,urine_albumin,kidney_risk
1,18.0,1.0,112.0,74.0,69.0,39.6,High
2,13.0,1.0,128.0,38.0,209.0,41.6,High
4,75.0,2.0,120.0,66.0,215.0,26.4,High
5,56.0,1.0,108.0,68.0,98.0,3.7,Low
6,18.0,1.0,112.0,68.0,18.0,0.7,Low

In [22]:
# saving data
# Raw clinical codes were transformed into human-readable features to improve interpretability and modeling.
df_final.to_csv("kidney_dataset.csv", index=False)
print("Final dataset saved as kidney_dataset.csv")

Final dataset saved as kidney_dataset.csv

In [23]:
# Training process is going to start
import pandas as pd

df = pd.read_csv("kidney_dataset.csv")

print(df.shape)
df.head()

(6166, 7)

,age,gender,systolic_bp,diastolic_bp,urine_creatinine,urine_albumin,kidney_risk
0,18.0,1.0,112.0,74.0,69.0,39.6,High
1,13.0,1.0,128.0,38.0,209.0,41.6,High
2,75.0,2.0,120.0,66.0,215.0,26.4,High
3,56.0,1.0,108.0,68.0,98.0,3.7,Low
4,18.0,1.0,112.0,68.0,18.0,0.7,Low

In [24]:
# Setting features and target
X = df[[
    'age',
    'gender',
    'systolic_bp',
    'diastolic_bp',
    'urine_creatinine',
    'urine_albumin'
]]

y = df['kidney_risk']

In [25]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

label_encoder.classes_

array(['High', 'Low', 'Medium'], dtype=object)

In [26]:
# Training, Testing and spliting
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)
# stratify isliye ke har class ka balance rahe.

In [27]:
# Model Train on Random Forest
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=200, random_state=42)

In [28]:
# Model Evaluation
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

Accuracy: 1.0
              precision    recall  f1-score   support

        High       1.00      1.00      1.00       512
         Low       1.00      1.00      1.00       478
      Medium       1.00      1.00      1.00       244

    accuracy                           1.00      1234
   macro avg       1.00      1.00      1.00      1234
weighted avg       1.00      1.00      1.00      1234

In [29]:
import joblib

joblib.dump(model, "kidney_model.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

print("Model and encoder saved successfully")

Model and encoder saved successfully